[package]
name = "many-time-pad"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.3.12", features = ["derive"]}
ratatui = { version = "0.22.0", features = ["all-widgets"]}
crossterm =  "0.26.1"